name: PullRequest

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  buildTest:
    name: Build & Test JDK ${{ matrix.java_version }}
    runs-on: macOS-14
    strategy:
      matrix:
        java_version: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
      - uses: gradle/wrapper-validation-action@v3.4.1
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Build project
        run: ./gradlew assembleDebug
  Check:
    name: Check
    runs-on: macOS-14
    strategy:
      matrix:
        java_version: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Code checks
        run: ./gradlew lint
      - name: Archive Lint report
        uses: actions/upload-artifact@v4.3.3
        if: ${{ always() }}
        with:
          if-no-files-found: error
          name: WebRTC-Lint-report
          path: ./**/build/reports/lint-results*.html
